# Based on documentation from actions/setup-node for installing private packages
# https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#use-private-packages
name: 'Setup NPM Package Project'
Description: 'Intialize an npm based project with private packages'
inputs:
  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
    default: '16'
  registry-url:
    description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.'
    default: 'https://npm.pkg.github.com'
  npm-auth-token:
    description: 'Token used to authenticate with npm'

runs:
  using: composite
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
    
    # Skip post-install scripts here, as a malicious
    # script could steal NODE_AUTH_TOKEN.
    - name: Download Package Dependencies
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-auth-token }}
        PACKAGE_DIRECTORIES: ${{ inputs.package-directories }}
    
    # `npm rebuild` will run all those post-install scripts for us.
    - name: Install Package Dependencies
      run: npm rebuild && npm run prepare --if-present
      env:
        PACKAGE_DIRECTORIES: ${{ inputs.package-directories }}
  