on:
  workflow_call:
    inputs:
      package-directories:
        description: 'space delimited list of package directories to build'
        default: '.'
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Project Workspace
        uses: 240tutoring/workflows/actions/setup-npm-package-project@main
        with:
          npm-auth-token: ${{ secrets.BUILDER_TOKEN }}
          package-directories: ${{ inputs.package-directories }}
      
      - name: Run tests
        run: npm run lint && npm run test

      - name: Create Release Pull Request / Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run changesets-version
          publish: npm run changesets-publish
        env:
          # Enable changesets action to create pr
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
          # Allow project publish steps to access private repositories
          BUILDER_TOKEN: ${{ secrets.BUILDER_TOKEN }} # allow private repo access
