on:
  workflow_call:
    inputs:
      package-directories:
        description: 'space delimited list of package directories to build'
        default: '.'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 240tutoring/workflows/actions/setup-npm-package-project@main
        with:
          npm-auth-token: ${{ secrets.BUILDER_TOKEN }}
          package-directories: ${{ inputs.package-directories }}
      - name: Run tests
        env:
          PACKAGE_DIRECTORIES: ${{ inputs.package-directories }}
        run: |
          for dir in $PACKAGE_DIRECTORIES; do
            cd "$GITHUB_WORKSPACE/$dir"
            npm run ci:test
          done

  package:
    needs: test
    if: ${{ needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: 240tutoring/workflows/actions/setup-npm-package-project@main
        with:
          npm-auth-token: ${{ secrets.BUILDER_TOKEN }}
          package-directories: ${{ inputs.package-directories }}
      - name: Build packages
        env:
          PACKAGE_DIRECTORIES: ${{ inputs.package-directories }}
        run: |
          for dir in $PACKAGE_DIRECTORIES; do
            cd "$GITHUB_WORKSPACE/$dir"
            npm run ci:build
            npm pack --pack-destination "$GITHUB_WORKSPACE/build"
          done
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}.zip
          path: ./build/
  