on:
  workflow_call:
    inputs:
      package-directories:
        description: 'space delimited list of package directories to build'
        default: '.'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 240tutoring/workflows/actions/setup-npm-package-project@main
        with:
          npm-auth-token: ${{ secrets.BUILDER_TOKEN }}
          package-directories: ${{ inputs.package-directories }}
      - name: Run tests
        run: npm run ci:test

  package:
    needs: test
    if: ${{ needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: 240tutoring/workflows/actions/setup-npm-package-project@main
        with:
          npm-auth-token: ${{ secrets.BUILDER_TOKEN }}
          package-directories: ${{ inputs.package-directories }}
      - name: Build packages
        run: |
          mkdir .cibuild
          npm run ci:build --if-present
          npm pack --pack-destination .cibuild
        env:
          BUILDER_TOKEN: ${{ secrets.BUILDER_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}.zip
          path: .cibuild
      - name: Publish packages
        run: npm run ci:publish --if-present
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
