on:
  workflow_call:
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Project Workspace
        uses: 240tutoring/workflows/actions/setup-npm-package-project@main
        with:
          npm-auth-token: ${{ secrets.BUILDER_TOKEN || secrets.GITHUB_TOKEN }}
      
      - name: Run tests
        run: npm run lint && npm run test

      # Verify that building will succeed if we are not on a branch that we are publishing from
      - name: Build
        if: github.ref != 'refs/heads/main' && hashFiles('.changeset/pre.json') == ''
        run: npm run build --if-present
        env:
          BUILDER_TOKEN: ${{ secrets.BUILDER_TOKEN || secrets.GITHUB_TOKEN }}

      # Publish from either the main branch, or any branch in pre release mode
      - name: Create Release Pull Request / Publish
        if: github.ref == 'refs/heads/main' || hashFiles('.changeset/pre.json') != ''
        uses: changesets/action@v1
        with:
          version: npm run changeset:version
          publish: npm run changeset:publish
        env:
          # Enable changesets action to create pr
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Allow project build steps to access private repositories
          BUILDER_TOKEN: ${{ secrets.BUILDER_TOKEN || secrets.GITHUB_TOKEN }}
          # Allow npm publish step to authenticate with github package registry
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
